name 'guests_cb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures guests_cb'
long_description 'Installs/Configures guests_cb'
version '0.1.0'

depends 'users'
depends 'build-essential'
depends 'apt'
depends 'sudo'
depends 'java'
depends 'nodejs'
depends 'simple-scala-sbt'
depends 'poise-python'
